language: ruby
rvm: 
  - 2.4.2
env:
  - DB =pgsql
services:
  - postgresql
before_script:
  - psql -c "create database travis;" -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate
script:
  - cp config/database.yml
  - bundle exec rspec spec
